sudo: required
dist: trusty
language: clojure
script: lein test
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
env:
  global:
  - secure: YxO9xYrhptJCmUKH46U8DmRWzO0VA0n/HxfhqoFEPqoD2GUWYKHcpviTh2f+yCu/JE0WpMW1ALJvHKfA9fpOOtvRFfTkRjftAsJzlBAtPx2eY8O0ClezId6ydILCyzCrIx1U1kFj7M8u5lpCo3Owov0fqV7Rek7VkCdBq5JFtboRTYyM2eRBYebv9MVbSQAJqH5rCdfs2K7FkJMZkoNNujzVgG8FrpGTnFdWNDi5iQ856VTcYYpc9BaQFYU9NdU7lmCS46ua74NYH6vfGVqgf2lsDq5YitWun71ER162iYpXiyf0fGQnIL+Z3mse4QMx7cqrDgA4Tkgg900fWOvpxU9atLjbkEjmfdf00jAiPbYwWLo6zEsZVJuZhmimQ1BnDibGa/URGUI3E8PC/4KnJCOIXo9eAEyNXIF+dA/33l/Ad6D24EJ3cGH6BhIclS7IbckjpUJynhVnXwAfE0ktLMTcJdPRlNYst44hBypNNv58SBow2O7wbdedKI9yMiJGvW301V5p10vyLh4XspqyyXWGkvtY77z7fLea7gjWbOomWi7qjPD/gcV18xqlBkF/dyt4BtQUFJBfL1snkRnBBMNSqf92fmLheT2gg9i8cUW50ecusAWBh1PbLn5Bq2pb7qp8vNtd8ebIwjpBtmNW1OmRmTnhhpExPpO1UAqLVGo=
  - secure: OnZTDB1Dd8Dk8CrcaFVz2jzU9wUOGZVkbM7hTVFl4MP64R9XXdpVhNdlrb1otyvZPzuQ/3IlVhCHSmO55GwCkroQL/s+CIrVbIAD4LzCHGOkSZ8dcZXZ5NEYchV8QsqK9hGO/Rt4W232f8BNTpA4B+Esq7mXkVIM8HA8SgHBFHkbGOHlkbpIGMpSucc7l1rusRBxA19hVyLwm4m/HQCPauKG/Fz2KNWBjg8ynN1e9xPAY3/N1UOy9h/GNxvgL6ORfwbY/6Czk5b/TSCj/IhEHejiOTFSGvphgoiB082FeGNYSlVojG9lfCQhva7MtzKEl1mDMYgPt2UU74HexM++X9tWNaHamyi+X15JJ8DP7yYh8W4oqW/Qi67kC5X1mKteO+tLejeWJTHvcP5dnTnnBppKqg96LvI9MkyQrjGseNBoH00DRCTKUmewiIGVHFOLmrl2BYbUNh0kP9vyAhn+BAXLp2NClLkQm9uK6vHgYUednFynyhX3o8FRr/M3k823iPNXFT3Xt4xdvavyRjC9EAURKm6ITxR3OEfdmx6VSLfuIJv5kP/LY0MdIJV/ZGxhdu5Nbbvji81Jc32ILB2UR5HPBUvKkgUPUQtQJhKLRvPJ5TF57ITAtrUZB7jbM3oGQPDucxQHn35VLfLWdPDphLr/JpMlaICieoLANx0Ygn4=
  - secure: 2ytJFus9jfmE1txuthq16N66hTNW1QQgUp4SoWZGsJLV4ut9qdYkZ9WSMndBDfza+B+2dARmAiW/POgmJAiOYxWbOBZa8Iq7kfAR+VDg2jrTBeWkMjNbjygjEfcKp/GV0oECMwdmqNHjRT7dZOgwwGGQ5oepbfVyr7Uy99+4JS4jRHY1eu8+X/fBGJHweWqWuRi9IM+ew5dkS8rXm0L1k6MQ+35/yd+OU+lI5lqnyZBh/6udswCs6lH6vqBbyGeflbpYnNAT15uSaIxWyy+OzE2FQIqMZb6etEeSdzT6aP+LhSyhBA2CmU7midL6QZ8GZnu5lyEWl8vG0JDHWrWZHkwwqgzUo5mlcTJNq7l5t56webm5K5BmkeFMC4cBeD1hk/BWQPwlbLxEtUuM7mdmiCFKl0KICnWqlNf8Fzsk/W11sarleTYTkdwkhksm/RxlolaapHhzrpq24ch3scz/Vt4m7JrEmtlmOSnf2SjP8WMwBamJSmFuvbsYRcFfiEocatcF1boXzTsNHETEm6zHTlAsc4XoKtwwTZfEiM16UwRXwTPLt9NUTw7ZxT7wvyzHinbu/cSG2eAsSVrWgKjMAH2kR20RMEFYLfOEM/OUJFMDYfCzax6RsN/+dixRM8Xdorzk6RA2gXJNMhql2Ms6yK4Z9cqv7Wb/V8T92ImBPww=
deploy:
- provider: script
  skip_cleanup: true
  script: bash travis/deploy.sh
  on:
    branch: master
